---
# tasks file for ansible-role-win-search-service
- name: Install Windows Feature - Search Service
  win_feature:
    name: search-service
    state: present

- name: Start Search Service
  win_service:
    name: WSearch
    start_mode: auto
    state: started
